#
#  Copyright (c) 2018-2024 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-operator
  namespace: eclipse-che
  labels:
    app: che-operator
    app.kubernetes.io/name: che
    app.kubernetes.io/instance: che
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: che-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: che-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: che-operator
        app.kubernetes.io/name: che
        app.kubernetes.io/instance: che
        app.kubernetes.io/part-of: che.eclipse.org
        app.kubernetes.io/component: che-operator
    spec:
      containers:
        - name: che-operator
          image: quay.io/eclipse/che-operator:3.15
          command:
            - /manager
          args:
            - --leader-elect
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 60000
              name: metrics
          env:
            - name: CHE_DEFAULT_SPEC_COMPONENTS_DASHBOARD_HEADERMESSAGE_TEXT
              value: ''
            - name: CHE_DEFAULT_SPEC_COMPONENTS_PLUGINREGISTRY_OPENVSXURL
              value: ''
            - name: CHE_DEFAULT_SPEC_DEVENVIRONMENTS_CONTAINERSECURITYCONTEXT
              value: '{"allowPrivilegeEscalation": true,"capabilities": {"add": ["SETGID",
                "SETUID"]}}'
            - name: CHE_DEFAULT_SPEC_DEVENVIRONMENTS_DEFAULTCOMPONENTS
              value: '[{"name": "universal-developer-image", "container": {"image":
                "registry.redhat.io/devspaces/udi-rhel8@sha256:d75f2568eb75892f06ac4eb4821268668b0727484fa085f9bb18df75b10aa4fd"}}]'
            - name: CHE_DEFAULT_SPEC_DEVENVIRONMENTS_DEFAULTEDITOR
              value: che-incubator/che-code/latest
            - name: CHE_DEFAULT_SPEC_DEVENVIRONMENTS_DISABLECONTAINERBUILDCAPABILITIES
              value: 'false'
            - name: CHE_FLAVOR
              value: devspaces
            - name: CHE_VERSION
              value: 3.15.0
            - name: CONSOLE_LINK_DISPLAY_NAME
              value: Eclipse Che
            - name: CONSOLE_LINK_IMAGE
              value: /dashboard/assets/branding/loader.svg
            - name: CONSOLE_LINK_NAME
              value: che
            - name: CONSOLE_LINK_SECTION
              value: Red Hat Applications
            - name: MAX_CONCURRENT_RECONCILES
              value: '1'
            - name: OPERATOR_NAME
              value: che-operator
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RELATED_IMAGE_che__centos__mongodb_36_centos7_devfile_registry_image_NRQXIZLTOQWWCOJRGVSGEN3CMVRWCOBXGE4TQZTDMQ3TQNRQGA4DMOJYHFTGKODBGMZDOYJRME2GMNRVGA4DAMRVMI3DIYLCGI4GMY3DG42DEM3CGI______
              value: quay.io/eclipse/che--centos--mongodb-36-centos7@sha256:a915db7beca87198fcd7860086989fe8a327a1a4f6508025b64ab28fcc7423b2
            - name: RELATED_IMAGE_che__centos__mongodb_36_centos7_devfile_registry_image_NRQXIZLTOQWWMZTEMYZDIMZRMJRGGNTEHFQTSZBSMEYDGZJZGVRGEYTFHBQWIYRUHFQWEOLFMFRTGMBRMYZDMODBGM2TAMZYMM4DIMRYHAZDKOLDGE______
              value: quay.io/eclipse/che--centos--mongodb-36-centos7@sha256:ffdf2431bbc6d9a9d2a03e95bbbe8adb49ab9eac301f268a35038c84288259c1
            - name: RELATED_IMAGE_che__centos__mysql_57_centos7_devfile_registry_image_NRQXIZLTOQWWKMBYMVSTIZBUGNRDOMZVGY3DANZWHA2WENRZMJSGKNRTGM2WKMRXMNTDEMDDGAZDAZRTGQ2WENTDGZRTKOJUGAYDCOBTHA4DENZWGQ______
              value: quay.io/eclipse/che--centos--mysql-57-centos7@sha256:e08ee4d43b7356607685b69bde6335e27cf20c020f345b6c6c59400183882764
            - name: RELATED_IMAGE_che__mariadb_devfile_registry_image_GEYC4NZOGEWTKYJYGAYDSMZWHFSWKNJXMM4DKYRWMY2GCMBYGQYDMMJUG5RGIOLDGUYDKY3EMU3GEOBSGUYGIMJWMEZDOZBSME2WMZLCMZSGKYLEG4______
              value: quay.io/eclipse/che--mariadb@sha256:5a8009369ee57c85b6f4a08406147bd9c505cde6b8250d16a27d2a5febfdead7
            - name: RELATED_IMAGE_che_code_devfile_registry_image_IBZWQYJSGU3DUNZUGZTDOMZVHE2DGMBSGU2DOM3BMEZWCMBWGAZGINBYGQYWGYLDMYYDSYZWMQ2TMMRWGEYDAYZRMM2DQNRVMQ3TKNJQMNRTCY3DHBSQ____
              value: quay.io/che-incubator/che-code@sha256:746f735943025473aa3a0602d4841cacf09c6d5626100c1c4865d7550cc1cc8e
            - name: RELATED_IMAGE_che_code_devfile_registry_image_NFXHG2LEMVZHG___
              value: quay.io/che-incubator/che-code@sha256:f24b9538fd50d63f665fec700e1d0f02ae451e103b138b600bd0fd944f51abbf
            - name: RELATED_IMAGE_che_server
              value: registry.redhat.io/devspaces/server-rhel8:3.15
            - name: RELATED_IMAGE_dashboard
              value: registry.redhat.io/devspaces/dashboard-rhel8:3.15
            - name: RELATED_IMAGE_devfile_registry
              value: registry.redhat.io/devspaces/devfileregistry-rhel8:3.15
            - name: RELATED_IMAGE_devworkspace_controller
              value: registry.redhat.io/devworkspace/devworkspace-rhel8-operator
            - name: RELATED_IMAGE_editor_definition_che_code_insiders_che_code_injector
              value: quay.io/che-incubator/che-code:insiders
            - name: RELATED_IMAGE_editor_definition_che_code_insiders_che_code_runtime_description
              value: quay.io/devfile/universal-developer-image:latest
            - name: RELATED_IMAGE_editor_definition_che_code_latest_che_code_injector
              value: quay.io/che-incubator/che-code:7.88.0
            - name: RELATED_IMAGE_editor_definition_che_code_latest_che_code_runtime_description
              value: quay.io/devfile/universal-developer-image:latest
            - name: RELATED_IMAGE_editor_definition_che_idea_latest_che_idea_injector
              value: quay.io/che-incubator/che-idea:latest
            - name: RELATED_IMAGE_editor_definition_che_idea_latest_che_idea_runtime_description
              value: quay.io/devfile/universal-developer-image:latest
            - name: RELATED_IMAGE_editor_definition_che_idea_next_che_idea_injector
              value: quay.io/che-incubator/che-idea:next
            - name: RELATED_IMAGE_editor_definition_che_idea_next_che_idea_runtime_description
              value: quay.io/devfile/universal-developer-image:latest
            - name: RELATED_IMAGE_editor_definition_che_idea_server_latest_editor_injector
              value: quay.io/che-incubator/che-idea-dev-server:latest
            - name: RELATED_IMAGE_editor_definition_che_idea_server_latest_editor_runtime
              value: quay.io/devfile/universal-developer-image:latest
            - name: RELATED_IMAGE_editor_definition_che_idea_server_next_editor_injector
              value: quay.io/che-incubator/che-idea-dev-server:next
            - name: RELATED_IMAGE_editor_definition_che_idea_server_next_editor_runtime
              value: quay.io/devfile/universal-developer-image:latest
            - name: RELATED_IMAGE_gateway_authentication_sidecar
              value: registry.redhat.io/openshift4/ose-oauth-proxy:v4.12
            - name: RELATED_IMAGE_gateway_authorization_sidecar
              value: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.12
            - name: RELATED_IMAGE_plugin_registry
              value: registry.redhat.io/devspaces/pluginregistry-rhel8:3.15
            - name: RELATED_IMAGE_pvc_jobs
              value: registry.redhat.io/ubi8/ubi-minimal:8.8
            - name: RELATED_IMAGE_single_host_gateway
              value: registry.redhat.io/devspaces/traefik-rhel8:3.15
            - name: RELATED_IMAGE_single_host_gateway_config_sidecar
              value: registry.redhat.io/devspaces/configbump-rhel8:3.15
            - name: RELATED_IMAGE_ubi_minimal_devfile_registry_image_
              value: registry.access.redhat.com/ubi8/ubi-minimal@sha256:5f1cd3422d5d46aea35dac80825dbcbd58213eef49c317f42a394345fb4e8ff1
            - name: RELATED_IMAGE_universal_developer_image_devfile_registry_image_IBZWQYJSGU3DUNZUGJRGMMRVMNRDCNBSHFSDSYZSGE3TOYRWGEYWMNJRGZSTSMBVGNRTQOBVHBSDAZTBHEYGGYZWME2TMMLCMRTDQMRSMFSTSNJTHFSQ____
              value: quay.io/devfile/universal-developer-image@sha256:742bf25cb1429d9c2177b611f516e9053c8858d0fa90cc6a561bdf822ae9539e
            - name: RELATED_IMAGE_universal_developer_image_devfile_registry_image_OVRGSOBNNRQXIZLTOQ______
              value: quay.io/devfile/universal-developer-image@sha256:742bf25cb1429d9c2177b611f516e9053c8858d0fa90cc6a561bdf822ae9539e
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 5
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 128Mi
      hostIPC: false
      hostNetwork: false
      hostPID: false
      restartPolicy: Always
      serviceAccountName: che-operator
      terminationGracePeriodSeconds: 20
