---
displayName: C/C++
description: C and C++ Developer Tools stack with GCC, cmake and make 
tags: ["Launch-Team", "C", "C++", "ms-tools", "GCC", "g++", "make", "cmake", "UBI8"]
icon: /images/type-cpp.svg
links:
  v2: https://github.com/mike4263/cpp-hello-world-cpptools
